export const LOCATIONS_REQUESTS = '@@LOMIS/locations/LOCATION_REQUESTS';
export const LOCATIONS_SUCCESS = '@@LOMIS/locations/LOCATION_SUCCESSS';
export const LOCATIONS_FAILURE = '@@LOMIS/locations/LOCATION_FAILURE';

export const USERS_REQUEST = '@@LOMIS/users/USERS_REQUEST';
export const USERS_SUCCESS = '@@LOMIS/users/USERS_SUCCESS';
export const USERS_FAILURE = '@@LOMIS/users/USERS_FAILURE';

export const ROLES_REQUEST = '@@LOMIS/users/ROLES_REQUEST';
export const ROLES_SUCCESS = '@@LOMIS/users/ROLES_SUCCESS';
export const ROLES_FAILURE = '@@LOMIS/users/ROLES_FAILURE';

export const SINGLE_USER_REQUEST = '@@LOMIS/users/SINGLE_USER_REQUEST';
export const SINGLE_USER_SUCCESS = '@@LOMIS/users/SINGLE_USER_SUCCESS';
export const SINGLE_USER_FAILURE = '@@LOMIS/users/SINGLE_USER_FAILURE';

export const CREATE_USER_REQUEST = '@@LOMIS/users/CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = '@@LOMIS/users/CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = '@@LOMIS/users/CREATE_USER_FAILURE';

export const EDIT_USER_REQUEST = '@@LOMIS/users/EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = '@@LOMIS/users/EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = '@@LOMIS/users/EDIT_USER_FAILURE';

export const CHANGE_PASSWORD_REQUEST = '@@LOMIS/users/CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = '@@LOMIS/users/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = '@@LOMIS/users/CHANGE_PASSWORD_FAILURE';

export const REQUEST_PASSWORD_RESET_REQUEST = '@@LOMIS/users/REQUEST_PASSWORD_RESET_REQUEST';
export const REQUEST_PASSWORD_RESET_SUCCESS = '@@LOMIS/users/REQUEST_PASSWORD_RESET_SUCCESS';
export const REQUEST_PASSWORD_RESET_FAILURE = '@@LOMIS/users/REQUEST_PASSWORD_RESET_FAILURE';

export const GET_RESET_TOKEN_REQUEST = '@@LOMIS/users/GET_RESET_TOKEN_REQUEST';
export const GET_RESET_TOKEN_SUCCESS = '@@LOMIS/users/GET_RESET_TOKEN_SUCCESS';
export const GET_RESET_TOKEN_FAILURE = '@@LOMIS/users/GET_RESET_TOKEN_FAILURE';

export const RESET_PASSWORD_REQUEST = '@@LOMIS/users/RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = '@@LOMIS/users/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = '@@LOMIS/users/RESET_PASSWORD_FAILURE';

export const CHANGE_USER_PASSWORD_REQUEST = '@@LOMIS/users/CHANGE_USER_PASSWORD_REQUEST';
export const CHANGE_USER_PASSWORD_SUCCESS = '@@LOMIS/users/CHANGE_USER_PASSWORD_SUCCESS';
export const CHANGE_USER_PASSWORD_FAILURE = '@@LOMIS/users/CHANGE_USER_PASSWORD_FAILURE';
